name: clerk
on:
  pull_request:
    types:
      - opened

jobs:
  clerk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Build
        run:  go build -v ./...
      - name: Unit Test
        run: go test -v ./...
